source "https://github.com/guillermo20/rappi-challenge-podspec-repo.git"
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.2'

target 'MovieDBRepository' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDBRepository
  pod 'MovieWebService',  :path => '../../network/MovieWebService'
  pod 'MovieDataBase',    :path => '../../database/MovieDataBase'

  target 'MovieDBRepositoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
