# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'MovieDBRepository' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDBRepository
  pod 'MovieWebService', :path => '../../network/MovieWebService'

  target 'MovieDBRepositoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
