
platform :ios, '12.2'

target 'RappiTechTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RappiTechTestApp
  pod 'MovieDBRepository',  :path => 'dependencies/repository/MovieDBRepository'


  target 'RappiTechTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
