
platform :ios, '12.2'

target 'MovieWebService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieWebService
  pod 'Alamofire', '~> 4.8.2'

  target 'MovieWebServiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
