source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.2'

target 'MoviesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesApptApp
  pod 'MovieDBRepository',  :path => 'dependencies/repository/MovieDBRepository'

  #in a perfect world these pods should be hosted on their own remote git repository
  #since this is a test they will be managed locally.

  pod 'MovieWebService',  :path => 'dependencies/network/MovieWebService'
  pod 'MovieDataBase',    :path => 'dependencies/database/MovieDataBase'

  target 'MoviesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
